In [1]:
import pandas as pd

from data.kbo.naver import NaverGame
from data.kbo.naver import SingleInning

from datetime import datetime

### Naver Text Crawl Test 1

* KIA(HT) vs Lotte(LT)
* Datetime 2024.9.28

In [2]:
log = NaverGame("HT", "LT", datetime(2024, 9, 28))
d_ = log.data()

In [3]:
inning_manager = SingleInning(1, "away")
xs, ys = list(), list()
for i, d in enumerate(d_):
    training = inning_manager.insert_log(d)
    if training is not None:
        x, y = training
        xs.append(x)
        ys.append(y)
    else:
        print(f"passing log {i}")
    
    if inning_manager.outs >= 3:
        inning_manager = inning_manager.advance_to_next()  # Change side or inning
        print(f"moved to inning {int(inning_manager.curr_inning)}, {inning_manager.home_away}")

passing log 0
moved to inning 1, home
passing log 5
moved to inning 2, away
passing log 10
moved to inning 2, home
passing log 14
moved to inning 3, away
passing log 20
moved to inning 3, home
passing log 25
moved to inning 4, away
passing log 30
moved to inning 4, home
passing log 34
passing log 39
passing log 43
moved to inning 5, away
passing log 47
moved to inning 5, home
passing log 55
passing log 64
passing log 66
moved to inning 6, away
passing log 69
moved to inning 6, home
passing log 76
passing log 82
moved to inning 7, away
passing log 89
passing log 92
passing log 94
moved to inning 7, home
passing log 96
passing log 99
moved to inning 8, away
passing log 101
moved to inning 8, home
passing log 105
passing log 108
moved to inning 9, away
passing log 110
moved to inning 9, home
passing log 115

In [9]:
total_logs = pd.concat([pd.concat(xs), pd.concat(ys)], axis=1).reset_index(drop=True)
total_logs['event_order'] = range(1, len(total_logs) + 1)

by_pitcher = total_logs.groupby("pitcher")
total_logs_segment = list()
for p in by_pitcher.groups.keys():
    df = by_pitcher.get_group(p).copy()
    df['totalBallCount'] = range(1, len(df) + 1)
    total_logs_segment.append(df)

total_logs = pd.concat(total_logs_segment).sort_values('event_order')
total_logs

,pitcher,batter,ballCount,type,speed,stance,crossPlateX,crossPlateY,topSz,bottomSz,...,az,strike,ball,out,base1,base2,base3,target,event_order,totalBallCount
0,52528,52605,1,투심,142.0,R,-0.078109,0.7083,3.35,1.643,...,-21.2339,0,0,0,0,0,0,1H,1,1
1,52528,52667,1,투심,142.0,R,0.538374,0.7083,3.306,1.621,...,-21.9436,0,0,0,1,0,0,T,2,2
2,52528,52667,2,체인지업,130.0,R,1.24071,0.7083,3.306,1.621,...,-25.0128,1,0,0,1,0,0,S,3,3
3,52528,52667,3,체인지업,132.0,R,0.105212,0.7083,3.306,1.621,...,-25.6861,2,0,0,1,0,0,B,4,4
4,52528,52667,4,체인지업,129.0,R,0.227236,0.7083,3.306,1.621,...,-29.0134,2,1,0,1,0,0,S,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,50662,62802,1,직구,147.0,L,-1.29195,0.7083,3.442,1.689,...,-23.5202,0,0,2,5,0,0,B,330,10
330,50662,62802,2,직구,144.0,L,-0.319255,0.7083,3.442,1.689,...,-19.6304,0,1,2,5,0,0,F,331,11
331,50662,62802,3,직구,145.0,L,-0.683633,0.7083,3.442,1.689,...,-21.119,1,1,2,5,0,0,S,332,12
332,50662,62802,4,포크,129.0,L,-1.01368,0.7083,3.442,1.689,...,-29.7194,2,1,2,5,0,0,B,333,13
333,50662,62802,5,직구,146.0,L,0.088372,0.7083,3.442,1.689,...,-17.7082,2,2,2,5,0,0,HO,334,14

In [10]:
total_logs.to_csv("checkup.csv")
total_logs

,pitcher,batter,ballCount,type,speed,stance,crossPlateX,crossPlateY,topSz,bottomSz,...,az,strike,ball,out,base1,base2,base3,target,event_order,totalBallCount
0,52528,52605,1,투심,142.0,R,-0.078109,0.7083,3.35,1.643,...,-21.2339,0,0,0,0,0,0,1H,1,1
1,52528,52667,1,투심,142.0,R,0.538374,0.7083,3.306,1.621,...,-21.9436,0,0,0,1,0,0,T,2,2
2,52528,52667,2,체인지업,130.0,R,1.24071,0.7083,3.306,1.621,...,-25.0128,1,0,0,1,0,0,S,3,3
3,52528,52667,3,체인지업,132.0,R,0.105212,0.7083,3.306,1.621,...,-25.6861,2,0,0,1,0,0,B,4,4
4,52528,52667,4,체인지업,129.0,R,0.227236,0.7083,3.306,1.621,...,-29.0134,2,1,0,1,0,0,S,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,50662,62802,1,직구,147.0,L,-1.29195,0.7083,3.442,1.689,...,-23.5202,0,0,2,5,0,0,B,330,10
330,50662,62802,2,직구,144.0,L,-0.319255,0.7083,3.442,1.689,...,-19.6304,0,1,2,5,0,0,F,331,11
331,50662,62802,3,직구,145.0,L,-0.683633,0.7083,3.442,1.689,...,-21.119,1,1,2,5,0,0,S,332,12
332,50662,62802,4,포크,129.0,L,-1.01368,0.7083,3.442,1.689,...,-29.7194,2,1,2,5,0,0,B,333,13
333,50662,62802,5,직구,146.0,L,0.088372,0.7083,3.442,1.689,...,-17.7082,2,2,2,5,0,0,HO,334,14

### Naver Text Crawl Test 2

* LG(LG) vs Samsung(SS)
* Datetime 2024.9.28

In [5]:
log = NaverGame("LG", "SS", datetime(2024, 9, 28))
d_ = log.data()

In [ ]:
inning_manager = SingleInning(1, "away")
xs, ys = list(), list()
for i, d in enumerate(d_):
    training = inning_manager.insert_log(d)
    if training is not None:
        x, y = training
        xs.append(x)
        ys.append(y)
    else:
        print(f"passing log {i}")
    
    if inning_manager.outs >= 3:
        inning_manager = inning_manager.advance_to_next()  # Change side or inning
        print(f"moved to inning {int(inning_manager.curr_inning)}, {inning_manager.home_away}")

In [ ]:
total_logs = pd.concat([pd.concat(xs), pd.concat(ys)], axis=1).reset_index(drop=True)

,pitcher,batter,ballCount,type,speed,stance,crossPlateX,crossPlateY,topSz,bottomSz,...,ax,ay,az,strike,ball,out,base1,base2,base3,target
0,68419,66108,1,직구,135.0,L,0.055886,0.7083,3.537,1.735,...,5.14102,25.715,-15.8062,0,0,0,0,0,0,T
1,68419,66108,2,슬라이더,129.0,L,-2.00202,0.7083,3.537,1.735,...,-3.02883,24.4232,-29.21,1,0,0,0,0,0,B
2,68419,66108,3,직구,136.0,L,-0.047835,0.7083,3.537,1.735,...,6.56085,24.6768,-16.5168,1,1,0,0,0,0,B
3,68419,66108,4,직구,134.0,L,0.182898,0.7083,3.537,1.735,...,6.21067,23.3726,-13.8033,1,2,0,0,0,0,1H
4,68419,65207,1,슬라이더,126.0,L,-0.434279,0.7083,3.172,1.556,...,-2.97056,17.962,-26.4789,0,0,0,1,0,0,T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309,50106,74540,1,직구,146.0,R,-0.741835,0.7083,3.457,1.696,...,-12.4524,28.2605,-14.0898,0,0,2,0,0,0,F
310,50106,74540,2,포크,133.0,R,-0.562511,0.7083,3.457,1.696,...,-11.0357,24.1281,-29.2383,1,0,2,0,0,0,S
311,50106,74540,3,직구,147.0,R,0.37857,0.7083,3.457,1.696,...,-12.1959,27.9171,-18.8438,2,0,2,0,0,0,B
312,50106,74540,4,포크,136.0,R,-0.581995,0.7083,3.457,1.696,...,-16.9712,25.6107,-28.9443,2,1,2,0,0,0,F
313,50106,74540,5,슬라이더,132.0,R,0.400314,0.7083,3.457,1.696,...,0.953085,28.3235,-31.7977,3,1,2,0,0,0,T

In [ ]:
total_logs.to_csv("checkup.csv")
total_logs